export const COLLAPSE_MENU = "COLLAPSE_MENU";
export const COLLAPSE_TOGGLE = "COLLAPSE_TOGGLE";
export const FULL_SCREEN = "FULL_SCREEN";
export const FULL_SCREEN_EXIT = "FULL_SCREEN_EXIT";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const NAV_CONTENT_LEAVE = "NAV_CONTENT_LEAVE";
export const NAV_COLLAPSE_LEAVE = "NAV_COLLAPSE_LEAVE";
export const SUBMITTING_REQUEST_STATUS = "SUBMITTING_REQUEST_STATUS";
export const LOADED_USER_AUTH_SUCCESS = "LOADED_USER_AUTH_SUCCESS";
export const LOADED_USER_PARAM_SUCCESS = "LOADED_USER_PARAM_SUCCESS";
export const LOADED_USER_INFO_SUCCESS = "LOADED_USER_INFO_SUCCESS";
export const LOADED_USER_FORGOT_SUCCESS = "LOADED_USER_FORGOT_SUCCESS";
export const LOADED_SETTING_INFO_SUCCESS = "LOADED_SETTING_INFO_SUCCESS";
export const LOADED_DATA_SUCCESS = "LOADED_DATA_SUCCESS";
export const LOADED_EMAIL_DATA_SUCCESS = "LOADED_EMAIL_DATA_SUCCESS";
export const LOADED_PAGE_DATA_SUCCESS = "LOADED_PAGE_DATA_SUCCESS";
export const LOADED_BRAND_DATA_SUCCESS = "LOADED_BRAND_DATA_SUCCESS";
export const LOAD_PAGINATION_DATA_SUCCESS = "LOAD_PAGINATION_DATA_SUCCESS";
export const LOAD_FORM_POP = "LOAD_FORM_POP";
export const NETWORK_REQUEST_STATUS = "NETWORK_REQUEST_STATUS";
export const TABLE_HEAD_REQUEST_STATUS = "TABLE_HEAD_REQUEST_STATUS";
export const LOAD_REQUEST_STATUS = "LOAD_REQUEST_STATUS";
export const LOADED_FAQ_DATA_SUCCESS = "LOADED_FAQ_DATA_SUCCESS";
export const LOADED_EMAIL_PARAM_SUCCESS = "LOADED_EMAIL_PARAM_SUCCESS";
export const LOAD_STATUS = "LOAD_STATUS";
export const LOAD_PATH_NAME = "LOAD_PATH_NAME";
export const LOADED_SUBSCRIPTION_DATA_SUCCESS =
  "LOADED_SUBSCRIPTION_DATA_SUCCESS";
export const LOADED_CUSTOMER_DATA_SUCCESS = "LOADED_CUSTOMER_DATA_SUCCESS";
export const LOADED_DASHBORD_INFO_SUCCESS = "LOADED_DASHBORD_INFO_SUCCESS";
export const LOADED_USER_NOTIFICATION_DATA_SUCCESS =
  "LOADED_USER_NOTIFICATION_DATA_SUCCESS";
export const LOADED_USER_LIST_DATA_SUCCESS = "LOADED_USER_LIST_DATA_SUCCESS";
export const LOADED_REQUEST_DATA_SUCCESS = "LOADED_REQUEST_DATA_SUCCESS";
export const LOADED_ADMIN_DATA_SUCCESS = "LOADED_ADMIN_DATA_SUCCESS";
export const LOADED_AUDITOR_DATA_SUCCESS = "LOADED_AUDITOR_DATA_SUCCESS";
export const LOADED_REGISTRATION_GROUP_DATA_SUCCESS =
  "LOADED_REGISTRATION_GROUP_DATA_SUCCESS";
export const LOADED_DOCUMENT_TYPE_DATA_SUCCESS =
  "LOADED_DOCUMENT_TYPE_DATA_SUCCESS";
export const LOADED_DOCUMENT_PARAM_SUCCESS = "LOADED_DOCUMENT_PARAM_SUCCESS";
export const LOADED_OTHER_DOCUMENT_SUCCESS = "LOADED_OTHER_DOCUMENT_SUCCESS";
export const LOADED_CONTACT_DATA_SUCCESS = "LOADED_CONTACT_DATA_SUCCESS";
export const LOADED_ID_DOCUMENT_SUCCESS = "LOADED_ID_DOCUMENT_SUCCESS";
export const LOADED_TOSTER_INFO_SUCCESS = "LOADED_TOSTER_INFO_SUCCESS";
export const LOADED_DIALOGOPEN_SUCCESS = "LOADED_DIALOGOPEN_SUCCESS";
export const LOADED_NOTIFICATION_COUNT_SUCCESS =
  "LOADED_NOTIFICATION_COUNT_SUCCESS";
export const LOAD_KEY_PERSON_DATA_SUCCESS = "LOAD_KEY_PERSON_DATA_SUCCESS";
export const LOADED_AUDIT_DATA_SUCCESS = "LOADED_AUDIT_DATA_SUCCESS";
export const LOADED_REGISTRATION_GROUP_LIST_SUCCESS =
  "LOADED_REGISTRATION_GROUP_LIST_SUCCESS";
export const LOADED_COMPANY_LIST_SUCCESS = "LOADED_COMPANY_LIST_SUCCESS";
export const LOADED_TRANSACTION_LIST_SUCCESS =
  "LOADED_TRANSACTION_LIST_SUCCESS";
export const LOADED_DOCUMENT_List_SUCCESS = "LOADED_DOCUMENT_List_SUCCESS";

export const LOADED_SELECTED_DOCUMENT_DATA_SUCCESS =
  "LOADED_SELECTED_DOCUMENT_DATA_SUCCESS";
