// eslint-disable-next-line import/no-anonymous-default-export
export default {
  isSuperUserAuth: false,
  isSubmitting: false,
  superUserParams: {},
  superUserInfo: {},
  isFrogot: false,
  isOpen: [], //for active default menu
  isTrigger: [], //for active default menu, set blank for horizontal
  isFullScreen: false, // static can't change
  collapseMenu: true,
  setting: {},
  emailData: [],
  requestParams: {},
  pageData: [],
  faqData: [],
  customerData: [],
  adminData: [],
  auditorData: [],
  isData: true,
  pagination: {},
  formPop: false,
  isFetching: false,
  isLoad: true,
  status: false,
  isHead: [],
  pathName: [],
  dashboard: {},
  userList: [],
  notificationList: [],
  notificationCount: 0,
  registrationgroupData: [],
  documentTypeData: [],
  documentParams: {},
  otherDocument: [],
  contactData: [],
  idDocument: [],
  toaster: {
    open: false,
    message: "test",
    severity: "success",
  },
  dialogOpen: false,
  keyPerson: [],
  auditData: [],
  registrationGroupList: [],
  companyList: [],
  transactionsList: [],
  documentList: [],
  selectedDocument: [],
};
