export const SUBMITTING_REQUEST_STATUS = "SUBMITTING_REQUEST_STATUS";
export const LOADED_USER_AUTH_SUCCESS = "LOADED_USER_AUTH_SUCCESS";
export const LOADED_USER_PARAM_SUCCESS = "LOADED_USER_PARAM_SUCCESS";
export const LOADED_USER_INFO_SUCCESS = "LOADED_USER_INFO_SUCCESS";
export const NETWORK_REQUEST_STATUS = "NETWORK_REQUEST_STATUS";
export const LOADED_SETTING_INFO_SUCCESS = "LOADED_SETTING_INFO_SUCCESS";
export const LOAD_HOME_PAGE_DATA_SUCCESS = "LOAD_HOME_PAGE_DATA_SUCCESS";
export const LOAD_PAGE_DATA_SUCCESS = "LOAD_PAGE_DATA_SUCCESS";
export const LOAD_FAQ_DATA_SUCCESS = "LOAD_FAQ_DATA_SUCCESS";
export const LOADED_TOASTER_INFO_SUCCESS = "LOADED_TOASTER_INFO_SUCCESS";
export const LOAD_PAGINATION_DATA_SUCCESS = "LOAD_PAGINATION_DATA_SUCCESS";
export const LOAD_KEY_PERSON_DATA_SUCCESS = "LOAD_KEY_PERSON_DATA_SUCCESS";
export const LOADED_DATA_SUCCESS = "LOADED_DATA_SUCCESS";
export const TABLE_HEAD_REQUEST_STATUS = "TABLE_HEAD_REQUEST_STATUS";
export const LOADED_DIALOGOPEN_SUCCESS = "LOADED_DIALOGOPEN_SUCCESS";
export const LOADED_NOTIFICATION_COUNT_SUCCESS =
  "LOADED_NOTIFICATION_COUNT_SUCCESS";
export const LOADED_USER_NOTIFICATION_DATA_SUCCESS =
  "LOADED_USER_NOTIFICATION_DATA_SUCCESS";
export const LOADED_AUDIT_DATA_SUCCESS = "LOADED_AUDIT_DATA_SUCCESS";
export const LOADED_REGISTRATION_GROUP_DATA_SUCCESS =
  "LOADED_REGISTRATION_GROUP_DATA_SUCCESS";
export const LOAD_TRANSACTION_DATA_SUCCESS = "LOAD_TRANSACTION_DATA_SUCCESS";
